# Generated by Django 4.1.1 on 2024-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
