# Generated by Django 4.1.1 on 2024-04-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'QuizQuestion'},
        ),
        migrations.AlterModelOptions(
            name='quiztype',
            options={'verbose_name_plural': 'QuizType'},
        ),
        migrations.AlterField(
            model_name='quiztype',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
